name: file_based_transaction_manager
description: Save a Copy from your files easily and rollback them any time.
version: 0.0.2
homepage: https://github.com/kareemradwan/FileBasedTransactionManager

environment:
  sdk: '>=2.18.1 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
